const types = {
  GET_15_POSTS: 'GET_15_POSTS',
  POSTS_ERROR: 'POSTS_ERROR',
  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST',
  SEARCH_POSTS: 'SEARCH_POSTS',
  LOADING_POSTS_TRUE: 'LOADING_POSTS_TRUE',
  POST_DELETE: 'POST_DELETE',
  CREATE_POST: 'CREATE_POST',

  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER: 'REGISTER',
  REGISTER_ERROR: 'REGISTER_ERROR',
  CHECK_PROFILE: 'CHECK_PROFILE',
  GET_PROFILE: 'GET_PROFILE',
  LOG_OUT: 'LOG_OUT',
  LOADING_PROFILE_TRUE: 'LOADING_PROFILE_TRUE',
  GET_MESSAGEES: 'GET_MESSAGES',
  GET_SENT_MESSAGES: 'GET_SENT_MESSAGES',
  VIEW_MESSAGE: 'VIEW_MESSAGE',

  GET_POST_COMMENTS: 'GET_POST_COMMENTS',
  LIKE_COMMENT: 'LIKE_COMMENT',
  DISLIKE_COMMENT: 'DISLIKE_COMMENT',
  COMMENT_POST: 'COMMENT_POST',
  COMMENT_DELETE: 'COMMENT_DELETE',
  GET_POST_COMMENTS_ONLY_POST: 'GET_POST_COMMENTS_ONLY_POST',

  MESSAGE_MODAL_SHOW: 'MESSAGE_MODAL_SHOW',
  MESSAGE_MODAL_HIDE: 'MESSAGE_MODAL_HIDE',

  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',

};
export default types;